version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    image: anastasiapetrova/foodgram_backend
    volumes:
      - static:/backend_static/
      - media:/app/media/
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    image: anastasiapetrova/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/