# Generated by Django 4.0 on 2023-07-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={
                'ordering':
                    ('-added',),
                    'verbose_name': 'Рецепт в списке покупок',
                    'verbose_name_plural': 'Рецепты в списке покупок'
                    },
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={
                'ordering':
                    ('-added',),
                    'verbose_name': 'Избранный рецепт',
                    'verbose_name_plural': 'Избранные рецепты'
                    },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={
                'ordering':
                    ('name',),
                    'verbose_name': 'Ингредиент',
                    'verbose_name_plural': 'Ингредиенты'
                    },
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={
                'ordering':
                    ('recipe',),
                    'verbose_name': 'Ингредиент',
                    'verbose_name_plural': 'Ингредиенты'
                    },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering':
                    ('-published',),
                    'verbose_name': 'Рецепт',
                    'verbose_name_plural': 'Рецепты'
                    },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={
                'ordering':
                    ('name',),
                    'verbose_name': 'Тэг',
                    'verbose_name_plural': 'Тэги'
                    },
        ),
    ]
